# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Illustration and Design by Karen Murray | A Rose Cast
email: hello@arosecast.com
description: A Rose Cast is a one-person studio producing illustration and design work for clients, both big and small, as well as a line of illustrative products ~ from art prints and stationery, to jewellery and homewares ~ sold both online and in physical stores.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.arosecast.com" # the base hostname & protocol for your site
twitter_username: arosecast
github_username:  arosecast

paginate: 5
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled: 'all'

# Build settings
markdown: kramdown
gems:
  - jekyll-archives
  - jekyll-paginate

exclude:
  - README.md
  - Procfile
  - Gemfile*
